In [2]:
# GUASSIAN MIXTURE
from sklearn.mixture import GaussianMixture
from sklearn.datasets import make_moons
X, y = make_moons(n_samples=1000, noise=0.05)


In [3]:
gm = GaussianMixture(n_components=3, n_init=10)
gm.fit(X)

GaussianMixture(n_components=3, n_init=10)

In [4]:
gm.weights_

array([0.21044847, 0.19938894, 0.59016259])

In [5]:
gm.means_

array([[ 1.72336424, -0.07149995],
       [-0.75328656,  0.56230467],
       [ 0.48271515,  0.26252803]])

In [6]:
gm.converged_ # si el algoritmo termina convergiendo

True

In [8]:
gm.n_iter_

16

In [9]:
gm.predict(X)

array([2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2,
       2, 0, 2, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 2, 2, 2, 0, 1, 2, 2, 0, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 0, 1, 2, 0, 0, 2, 2, 2,
       2, 2, 0, 0, 0, 2, 2, 1, 2, 0, 2, 2, 0, 1, 1, 2, 2, 0, 1, 2, 2, 1,
       1, 2, 0, 2, 2, 1, 2, 0, 0, 0, 1, 2, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0,
       0, 1, 2, 2, 2, 2, 1, 2, 0, 1, 2, 2, 2, 0, 2, 0, 2, 2, 1, 0, 1, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       1, 2, 2, 2, 1, 2, 1, 0, 0, 0, 2, 2, 0, 1, 0, 0, 2, 1, 2, 0, 0, 1,
       1, 0, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 0,
       2, 2, 0, 2, 2, 0, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 1, 2, 1, 2, 1, 2, 2, 0, 2, 2, 2, 0, 1, 2, 2, 1, 1, 2, 2, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 1, 2, 2,
       2, 1, 2, 1, 1, 0, 1, 2, 1, 1, 2, 2, 2, 2, 0, 2, 1, 0, 0, 1, 1, 2,
       0, 2, 1, 2, 2, 2, 1, 0, 0, 2, 2, 0, 0, 2, 2,

In [10]:
gm.predict_proba(X)

array([[4.05867651e-026, 9.92279459e-084, 1.00000000e+000],
       [4.00407994e-119, 2.64509862e-009, 9.99999997e-001],
       [3.80777909e-034, 5.28604627e-069, 1.00000000e+000],
       ...,
       [8.03011749e-005, 6.25613284e-152, 9.99919699e-001],
       [1.70533060e-015, 2.10454989e-108, 1.00000000e+000],
       [7.72235331e-193, 9.96361397e-001, 3.63860277e-003]])

In [11]:
X_new, y_new = gm.sample(6)

In [12]:
X_new

array([[ 1.42704077, -0.46437196],
       [ 1.79348578, -0.17485483],
       [-0.51190583,  0.85220337],
       [ 0.16248851,  0.75504802],
       [ 0.50345764, -0.14892153],
       [ 0.70263898,  0.49855959]])

In [13]:
y_new# label del cluster

array([0, 0, 1, 2, 2, 2])

In [15]:
#optimal number of clusters
from sklearn.mixture import BayesianGaussianMixture
import numpy as np

bgm = BayesianGaussianMixture(n_components=10, n_init=10)
bgm.fit(X)
np.round(bgm.weights_, 2)


array([0.13, 0.13, 0.14, 0.12, 0.14, 0.1 , 0.12, 0.12, 0.  , 0.  ])