In [1]:
from sklearn.linear_model import Ridge
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import Pipeline


In [2]:
# regularization is typically achieved by constraining the weights of the model
# ridge resta el peso de cada factor teetha por una constante alpha: alpha*|theeta**2|
m = 100 
X = 6 * np.random.rand(m, 1) - 3 
y = 0.5 * X**2 + X + 2 + np.random.randn(m, 1)

ridge_reg = Ridge(alpha=1, solver="cholesky")
ridge_reg.fit(X, y)
ridge_reg.predict([[1.5]])

array([[4.87026836]])

In [3]:
sgd_reg = SGDRegressor(penalty="l2") # l2 es ridge reg
sgd_reg.fit(X, y.ravel())
sgd_reg.predict([[1.5]])

array([4.83373116])

In [4]:
# lasso regression alpha*|theeta|
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.1)
lasso_reg.fit(X, y)
lasso_reg.predict([[1.5]])


array([4.82168858])

In [5]:
sgd_reg = SGDRegressor(penalty="l1") # l1 es lasso reg
sgd_reg.fit(X, y.ravel())
sgd_reg.predict([[1.5]])

array([4.84873649])

In [6]:
#Ridge default method of regularization, but Lasso or Net are usefull if there is a lot of overfitting
from sklearn.linear_model import ElasticNet
elastic_net = ElasticNet(alpha=0.1, l1_ratio=0.5)
elastic_net.fit(X, y)
elastic_net.predict([[1.5]])

array([4.82299273])