In [1]:
from sklearn.datasets import fetch_openml
from sklearn.linear_model import LogisticRegression 

mnist = fetch_openml('mnist_784', version=1)
X, y = mnist['data'], mnist['target']
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]

In [6]:
# using clustering for semisupervised learning
n_labeled = 50
log_reg = LogisticRegression()
log_reg.fit(X_train[:n_labeled], y_train[:n_labeled])

log_reg.score(X_test, y_test)

0.6295

In [19]:
# mejorar la performance a patir de hace kmeans
import numpy as np
from sklearn.cluster import KMeans


k=50
kmeans = KMeans(n_clusters=k)
X_digits_dist = kmeans.fit_transform(X_train)
representative_digit_idx = np.argmin(X_digits_dist, axis=0)
X_representative_digits = X_train[representative_digit_idx]


In [20]:
y_representative_digits = np.array([4, 8, 0, 6, 8, 3, 7,7,9,2,5,5,8,5,2,1,2,9,6,1\
                                    ,1,6,9,0,8,3,0,7,4,1,6,5,2,4,1,8,6,3,9,2,4,2,9,\
                                    4,7, 6, 2, 3, 1, 1])


In [23]:
log_reg1 = LogisticRegression()
log_reg1.fit(X_representative_digits, y_representative_digits)
log_reg1.score(X_test, y_test)

0.0

In [24]:
# label propagation
y_train_propagated = np.empty(len(X_train), dtype=np.int32)
for i in range(k):
    y_train_propagated[kmeans.labels_ == i] = y_representative_digits[i]



In [26]:
#DBSCAN- density clustering 
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons

X, y = make_moons(n_samples=1000, noise=0.05)


In [28]:
dbscan = DBSCAN(eps=0.05, min_samples=5) 
dbscan.fit(X)

DBSCAN(eps=0.05)

In [29]:
dbscan.labels_

array([ 0,  1,  1,  0,  1, -1,  1,  2,  1,  0,  1,  1,  0,  2,  0,  3,  1,
        0,  1,  1,  1,  2,  2,  2,  2,  1,  1,  1,  1,  1,  1,  1,  2,  0,
        1,  0,  2,  1,  0,  1,  1,  0,  2,  1,  1,  2,  0,  1,  1,  1,  1,
        1,  2,  2,  1,  2,  1,  0,  0,  2,  1, -1,  1,  0,  0,  1,  0, -1,
        1,  1,  1,  1,  1,  1,  1,  3,  0,  1, -1,  0,  1,  3,  1,  2,  1,
        0,  1,  2,  1,  2,  1,  2,  1,  1,  1,  0,  1,  2,  1,  1,  0,  1,
        1,  1,  1,  2,  3,  0,  0,  1,  1,  1,  3,  1,  1, -1,  1,  2,  0,
        1,  0,  1,  0,  3, -1,  0,  1,  1,  1,  0,  0,  2,  1,  0,  2,  1,
        1,  2,  0, -1,  1,  1,  0,  1,  0,  2,  2,  0,  2,  1,  1,  1, -1,
        2,  1,  1,  3,  2,  1,  2,  0,  2,  3,  0,  1,  2,  4,  1,  1,  3,
        0,  2,  1,  0,  1,  1, -1,  1,  2,  0,  1,  1,  2,  1,  2,  1,  1,
        0,  1,  0,  0, -1, -1,  0,  0,  0,  1,  1,  1,  1,  2,  1,  1,  0,
       -1,  1, -1,  1,  1,  3,  1,  1,  2,  1,  1,  2,  2,  2,  0,  1,  1,
        1,  0,  1,  1,  2

In [30]:
len(dbscan.core_sample_indices_)

828

In [31]:
dbscan.core_sample_indices_

array([  0,   1,   3,   4,   6,   7,   9,  11,  12,  13,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  31,
        32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  43,  45,  46,
        47,  48,  49,  50,  52,  53,  54,  56,  57,  58,  59,  60,  62,
        63,  64,  65,  66,  69,  70,  72,  74,  75,  76,  79,  80,  81,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  97, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
       110, 111, 112, 114, 116, 117, 118, 119, 120, 121, 122, 123, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 154,
       155, 156, 157, 158, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       170, 171, 172, 173, 174, 175, 177, 178, 179, 180, 181, 182, 183,
       184, 185, 186, 187, 188, 190, 194, 195, 196, 197, 198, 199, 200,
       201, 202, 203, 205, 207, 208, 209, 210, 211, 212, 213, 21

In [32]:
dbscan.components_

array([[ 0.49368034, -0.37932566],
       [ 0.95224362,  0.14002444],
       [ 0.62815725, -0.40453274],
       ...,
       [-0.65394551,  0.70051783],
       [ 1.61994907, -0.31510367],
       [ 0.20802561, -0.14515048]])

In [35]:
# DBSCAN - utilizarlo con knclassifier- usando los core classifiers
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=50) 
knn.fit(dbscan.components_, dbscan.labels_[dbscan.core_sample_indices_])


KNeighborsClassifier(n_neighbors=50)

In [36]:
X_new = np.array([[-0.5, 0], [0, 0.5], [1, -0.1], [2, 1]])

knn.predict(X_new)

array([1, 3, 1, 2], dtype=int64)

In [37]:
knn.predict_proba(X_new)

array([[0.  , 0.76, 0.  , 0.24, 0.  ],
       [0.  , 0.  , 0.  , 1.  , 0.  ],
       [0.2 , 0.7 , 0.  , 0.  , 0.1 ],
       [0.  , 0.  , 1.  , 0.  , 0.  ]])

In [38]:
y_dist, y_pred_idx = knn.kneighbors(X_new, n_neighbors=1)


In [39]:
y_pred = dbscan.labels_[dbscan.core_sample_indices_][y_pred_idx]
y_pred[y_dist > 0.2] = -1
y_pred.ravel()

array([-1,  3,  4, -1], dtype=int64)